{% set name = "asynch" %}
{% set version = "0.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/long2ice/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ef29798b5f02d999543b7f0dffebf6de963835165d72fc5ae9ebba7e738a0bf5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<311]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - poetry-core
    - setuptools
    - cython >=3.1
  run:
    - python
    - ciso8601 >=2.3.2
    - tzlocal >=5.3.1
    - tzdata  # [win]
  run_constrained:
    - clickhouse-cityhash >=1.0.2.4
    - lz4 >=4.4.3
    - python-zstd >=1.5.6.6  # [py<314]

test:
  source_files:
    - tests
  imports:
    - asynch
    - asynch.proto
    - asynch.proto.columns
    - asynch.proto.compression
    - asynch.proto.settings
    - asynch.proto.streams
    - asynch.proto.utils
  commands:
    - pip check
  requires:
    - pip
    - pytest

about:
  home: https://github.com/long2ice/asynch
  summary: An asyncio ClickHouse Python Driver with native (TCP) interface support.
  description: |
    asynch is an asynchronous ClickHouse Python driver with native TCP interface support,
    which reuses most of clickhouse-driver features and complies with PEP249.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/long2ice/asynch
  doc_url: https://github.com/long2ice/asynch/blob/dev/README.md

extra:
  recipe-maintainers:
    - Jrice1317
