{% set name = "asynch" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15ef9517bb093dfd5a0f1f31cc31e0da84543eead0269345052922cf399d280e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - leb128
    - pytz
    - lz4
    - python-zstd
    - tzlocal
    - ciso8601
    # not available on windows
    - clickhouse-cityhash  # [unix]

test:
  imports:
    - asynch
    - asynch.proto
    - asynch.proto.columns
    - asynch.proto.compression
    - asynch.proto.settings
    - asynch.proto.streams
    - asynch.proto.utils
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/long2ice/asynch
  summary: An asyncio ClickHouse Python Driver with native (TCP) interface support.
  description: |
    asynch is an asynchronous ClickHouse Python driver with native TCP interface support,
    which reuses most of clickhouse-driver features and complies with PEP249.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/long2ice/asynch
  doc_url: https://github.com/long2ice/asynch

extra:
  recipe-maintainers:
    - Jrice1317
